"""
Emit the two appendix tables of the TMLR manuscript straight from the CSVs
analysis/analyze_power_and_ci.py wrote, so no number is transcribed by hand.

Scope matches the TMLR version: the five scorer variants of three families,
not the eight scorers of the earlier draft (see make_figure_power_tmlr.py).

    python3 analysis/make_tables_power_tmlr.py --out-dir paper/tmlr/tables
"""

from __future__ import annotations

import argparse
from pathlib import Path

import pandas as pd

ROOT = Path(__file__).resolve().parents[1]

GROUPS = [
    (r"Geometry metric vs.\ $\lambda_{\mathrm{orth}}$ (Section~\ref{sec:geometry-changes})", "E1", [
        ("condition_number", "Condition number"),
        ("fisher_ratio_HL", "Fisher ratio (Hotelling--Lawley)"),
        ("fisher_ratio_scalar", "Fisher ratio (decoupled scalar)"),
        ("mardia_kurtosis_b", r"Mardia's kurtosis ($b$)"),
        ("mardia_kurtosis_z", r"Mardia's kurtosis ($z$)"),
    ]),
    (r"Geometry metric vs.\ Mahalanobis AUROC (Section~\ref{sec:geometry-auroc})", "E2", [
        ("condition_number", "Condition number"),
        ("fisher_ratio_HL", "Fisher ratio (Hotelling--Lawley)"),
        ("fisher_ratio_scalar", "Fisher ratio (decoupled scalar)"),
        ("mardia_kurtosis_b", r"Mardia's kurtosis ($b$)"),
        ("mardia_kurtosis_z", r"Mardia's kurtosis ($z$)"),
    ]),
    (r"Directed scorer AUROC vs.\ $\lambda_{\mathrm{orth}}$ (Section~\ref{sec:generalizes})", "E2.6", [
        ("mahalanobis", "Mahalanobis"),
        ("cosine", "Cosine-to-centroid"),
        ("knn_k1", r"$k$-NN ($k=1$)"),
        ("knn_k10", r"$k$-NN ($k=10$)"),
        ("knn_k50", r"$k$-NN ($k=50$)"),
    ]),
    (r"Domain-probe AUROC vs.\ $\lambda_{\mathrm{orth}}$ (Section~\ref{sec:decodable})", "E2.7", [
        ("logistic_regression", "Logistic regression"),
        ("linear_svm", "Linear SVM"),
        ("random_forest", "Random forest"),
    ]),
]

DESIGN_ROW = {
    "A (n=13, continuous-continuous)": (r"A: continuous--continuous", r"$13!$"),
    "B (5/5/3 ladder, n=13)": (r"B: 5/5/3 ordered ladder", "72,072"),
    "B (3/3/3 common-seed, n=9)": (r"B: 3/3/3 common-seed subset", "1,680"),
}


def design_table(summary: pd.DataFrame) -> str:
    rows = []
    for design, (label, null_space) in DESIGN_ROW.items():
        r = summary[summary["design"] == design].iloc[0]
        rows.append(
            f"{label} & {int(r['n'])} & {null_space} & {r['max_attainable_abs_tau']:.3f} & "
            f"{r['tau_crit']:.3f} & {r['power_at_tau_0.3']:.2f} & {r['power_at_tau_0.5']:.2f} & "
            f"{r['mde_power80']:.2f} \\\\")
    body = "\n".join(rows)
    return rf"""% generated by analysis/make_tables_power_tmlr.py from
% results/power_design_summary.csv -- do not edit by hand.
\begin{{table}}[t]
\centering
\caption{{Detectability of the two permutation designs used in this study.
Design~A is the continuous--continuous test of a geometry metric against
Mahalanobis AUROC (Section~\ref{{sec:geometry-auroc}}); Design~B is the ordered
ladder used for every test against $\lambda_{{\mathrm{{orth}}}}$
(Sections~\ref{{sec:geometry-changes}}, \ref{{sec:generalizes}} and
\ref{{sec:decodable}}). ``Null space'' is the number of distinct label
arrangements enumerated for the exact test.
$\tau_{{\mathrm{{crit}}}}$ is the smallest $|\tau|$ attainable at that design whose
two-sided exact permutation $p$-value reaches $0.05$: no dataset, however clean,
can produce a significant association below it. Power is computed by simulation
($2\times10^{{4}}$ datasets per grid point, common random numbers) under an
alternative whose expected value of the reported statistic equals the stated
$\tau$ --- bivariate normal for Design~A, a linear dose shift
$y = \theta d + \varepsilon$ for Design~B. MDE$_{{80\%}}$ is the expected $\tau$ at
which power first reaches $0.80$.}}
\label{{tab:power-design}}
\footnotesize
\begin{{tabular}}{{lccccccc}}
\toprule
 & & Null & Max. & & \multicolumn{{2}}{{c}}{{Power at}} & \\
\cmidrule(lr){{6-7}}
Design & $n$ & space & $|\tau|$ & $\tau_{{\mathrm{{crit}}}}$ & $\tau=0.3$ & $\tau=0.5$ & MDE$_{{80\%}}$ \\
\midrule
{body}
\bottomrule
\end{{tabular}}
\end{{table}}
"""


def ci_table(ci: pd.DataFrame) -> str:
    idx = ci.set_index(["family", "test"])
    rows = []
    for gi, (heading, family, tests) in enumerate(GROUPS):
        if gi:
            rows.append(r"\addlinespace")
        rows.append(rf"\multicolumn{{4}}{{l}}{{\emph{{{heading}}}}} \\")
        rows.append(r"\addlinespace[0.15em]")
        for test, label in tests:
            r = idx.loc[(family, test)]
            tau = f"${r['tau']:+.3f}$".replace("+", r"\phantom{-}")
            if bool(r["at_design_ceiling"]):
                rows.append(rf"\quad {label} & {tau} & \multicolumn{{2}}{{c}}{{at design ceiling --- see note}} \\")
            else:
                rows.append(
                    rf"\quad {label} & {tau} & $[{r['ci_lo']:+.3f},\ {r['ci_hi']:+.3f}]$ & "
                    rf"{r['largest_effect_not_excluded']:.2f} \\")
    body = "\n".join(rows).replace("+0.", "\\phantom{-}0.")
    return rf"""% generated by analysis/make_tables_power_tmlr.py from
% results/kendall_tau_ci.csv -- do not edit by hand.
\begin{{table}}[t]
\centering
\caption{{Every Kendall's $\tau$ reported in this paper with a 95\% bootstrap
confidence interval ($2\times10^{{4}}$ stratified resamples, bias-corrected and
accelerated; resampling is within-rung, so the 5/5/3 design is held fixed).
``Largest $|\tau|$ not excluded'' is the interval endpoint furthest from zero:
the effect size each non-significant result still permits.}}
\label{{tab:tau-ci}}
\small
\begin{{tabular}}{{lccc}}
\toprule
Test & $\tau$ & 95\% CI & Largest $|\tau|$ not excluded \\
\midrule
{body}
\bottomrule
\end{{tabular}}

\vspace{{0.25cm}}
\begin{{minipage}}{{\textwidth}}
% undo the \centering of the enclosing table, so the note sets as a paragraph
\leftskip=0pt \rightskip=0pt \parfillskip=0pt plus 1fil
\small \emph{{Note.}} Condition number vs.\ $\lambda_{{\mathrm{{orth}}}}$ attains
$\tau = 0.840$, the maximum value the 5/5/3 design permits (a perfectly monotone
ladder). Every bootstrap resample therefore lies at or below the observed value,
the resampling distribution is one-sided by construction, and no bootstrap
interval is valid; the exact permutation $p$-value ($2.8\times10^{{-5}}$) is the
meaningful inference for that effect. Of the seventeen non-significant
associations, none has an interval that excludes $|\tau| = 0.3$.
\end{{minipage}}
\end{{table}}
"""


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--results-dir", type=Path, default=ROOT / "results")
    ap.add_argument("--out-dir", type=Path, default=ROOT / "paper" / "tmlr" / "tables")
    args = ap.parse_args()

    summary = pd.read_csv(args.results_dir / "power_design_summary.csv")
    ci = pd.read_csv(args.results_dir / "kendall_tau_ci.csv")

    args.out_dir.mkdir(parents=True, exist_ok=True)
    (args.out_dir / "table_power_design.tex").write_text(design_table(summary))
    (args.out_dir / "table_tau_ci.tex").write_text(ci_table(ci))
    print(f"wrote {args.out_dir}/table_power_design.tex and table_tau_ci.tex")


if __name__ == "__main__":
    main()
