"""
Before/after table for the ladder going from 13 to 15 checkpoints.

"Before" is read from git (the committed n=13 result files), not transcribed
from the manuscript, so the comparison cannot drift from what was published.

    git show HEAD:results/<f> > <before_dir>/<f>     # done by the caller
    python3 analysis/compare_n13_n15.py <before_dir>
"""

from __future__ import annotations

import sys
from pathlib import Path

import pandas as pd

ROOT = Path(__file__).resolve().parents[1]
RUNGS = ["runA_grl", "runB_orth1", "runB"]
GEO = ["condition_number", "fisher_ratio_HL", "fisher_ratio_scalar",
       "mardia_kurtosis_b", "mardia_kurtosis_z"]


def fmt(v, big=1e3):
    if pd.isna(v):
        return "--"
    return f"{v:,.1f}" if abs(v) >= big else (f"{v:.3f}" if abs(v) >= 0.01 else f"{v:.4f}")


def ms(df, col, rung):
    s = df[df.rung == rung][col]
    return f"{fmt(s.mean())} ± {fmt(s.std())}"


def main() -> None:
    before = Path(sys.argv[1])
    cur = ROOT / "results"
    out = []

    b1, c1 = pd.read_csv(before / "e1_geometry_metrics.csv"), pd.read_csv(cur / "e1_geometry_metrics.csv")
    out.append("## Bảng 1 — geometry theo nấc (mean ± SD)\n")
    out.append("| metric | nấc | trước (n=13) | sau (n=15) |")
    out.append("|---|---|---|---|")
    for m in GEO:
        for r in RUNGS:
            a, b = ms(b1, m, r), ms(c1, m, r)
            mark = "" if a == b else "  **đổi**"
            out.append(f"| `{m}` | `{r}` | {a} | {b}{mark} |")

    b2, c2 = pd.read_csv(before / "e2_auroc.csv"), pd.read_csv(cur / "e2_auroc.csv")
    out.append("\n## Bảng 2 — Mahalanobis AUROC theo nấc\n")
    out.append("| nấc | trước | sau |")
    out.append("|---|---|---|")
    for r in RUNGS:
        for col in ["auroc", "fpr95"]:
            out.append(f"| `{r}` {col} | {ms(b2, col, r)} | {ms(c2, col, r)} |")

    for name, key, label in [("e1_kendall_tau.csv", "metric", "E1 — geometry vs λ_orth"),
                             ("e2_kendall_tau.csv", "metric", "E2 — geometry vs Mahalanobis AUROC"),
                             ("e2_6_kendall_tau.csv", "scorer", "E2.6 — scorer AUROC vs λ_orth"),
                             ("e2_7_kendall_tau.csv", "probe", "E2.7 — probe AUROC vs λ_orth")]:
        b, c = pd.read_csv(before / name), pd.read_csv(cur / name)
        tcol = "tau_full" if "tau_full" in b.columns else "tau"
        pcol = ("p_full_exact" if "p_full_exact" in b.columns
                else ("p_exact" if "p_exact" in b.columns else None))
        out.append(f"\n## {label}\n")
        out.append("| | τ trước | p trước | τ sau | p sau |")
        out.append("|---|---|---|---|---|")
        bi, ci = b.set_index(key), c.set_index(key)
        for k in ci.index:
            tb = fmt(bi.loc[k, tcol]) if k in bi.index else "--"
            pb = f"{bi.loc[k, pcol]:.3g}" if (k in bi.index and pcol) else "--"
            out.append(f"| `{k}` | {tb} | {pb} | {fmt(ci.loc[k, tcol])} | {ci.loc[k, pcol]:.3g} |")

    b7, c7 = pd.read_csv(before / "e2_7_domain_probe.csv"), pd.read_csv(cur / "e2_7_domain_probe.csv")
    out.append("\n## Bảng 4 — probe AUROC theo nấc (mean)\n")
    out.append("| nấc | probe | trước | sau |")
    out.append("|---|---|---|---|")
    for r in RUNGS:
        for p in sorted(c7.probe.unique()):
            a = b7[(b7.rung == r) & (b7.probe == p)].domain_auroc.mean()
            n = c7[(c7.rung == r) & (c7.probe == p)].domain_auroc.mean()
            out.append(f"| `{r}` | {p} | {fmt(a)} | {fmt(n)} |")

    text = "\n".join(out)
    (ROOT / "docs" / "n13_vs_n15.md").write_text(
        "# Ladder 13 -> 15 checkpoints: every number that moves\n\n"
        "Generated by `analysis/compare_n13_n15.py`; \"before\" read from git, "
        "not from the manuscript.\n\n" + text + "\n")
    print(text)


if __name__ == "__main__":
    main()
